// Seed dictionary — pre-stemmed keys, cnt=2 so personal history quickly wins
// Source: speclocalclassifier.md §10

export const SEED: Array<{ word: string; category: string; cnt: number }> = [
  // Продукты
  { word: 'продукт',    category: 'Продукты', cnt: 2 },
  { word: 'вкусвилл',   category: 'Продукты', cnt: 2 },
  { word: 'пятёрочк',   category: 'Продукты', cnt: 2 },
  { word: 'перекрест',  category: 'Продукты', cnt: 2 },
  { word: 'магнит',     category: 'Продукты', cnt: 2 },
  { word: 'лент',       category: 'Продукты', cnt: 2 },
  { word: 'ашан',       category: 'Продукты', cnt: 2 },
  { word: 'дикси',      category: 'Продукты', cnt: 2 },
  { word: 'лавк',       category: 'Продукты', cnt: 2 },
  { word: 'мираторг',   category: 'Продукты', cnt: 2 },
  { word: 'овощ',       category: 'Продукты', cnt: 2 },
  { word: 'фрукт',      category: 'Продукты', cnt: 2 },
  { word: 'молок',      category: 'Продукты', cnt: 2 },
  { word: 'хлеб',       category: 'Продукты', cnt: 2 },
  { word: 'мяс',        category: 'Продукты', cnt: 2 },
  { word: 'супермаркет', category: 'Продукты', cnt: 2 },
  // Кафе
  { word: 'кафе',       category: 'Кафе', cnt: 2 },
  { word: 'кофе',       category: 'Кафе', cnt: 2 },
  { word: 'ресторан',   category: 'Кафе', cnt: 2 },
  { word: 'пицц',       category: 'Кафе', cnt: 2 },
  { word: 'шаурм',      category: 'Кафе', cnt: 2 },
  { word: 'столов',     category: 'Кафе', cnt: 2 },
  { word: 'бар',        category: 'Кафе', cnt: 2 },
  { word: 'мороженое',  category: 'Кафе', cnt: 2 },
  { word: 'суши',       category: 'Кафе', cnt: 2 },
  { word: 'доставк',    category: 'Кафе', cnt: 2 },
  // Транспорт
  { word: 'маршрутк',   category: 'Транспорт', cnt: 2 },
  { word: 'такс',       category: 'Транспорт', cnt: 2 },
  { word: 'метро',      category: 'Транспорт', cnt: 2 },
  { word: 'автобус',    category: 'Транспорт', cnt: 2 },
  { word: 'бензин',     category: 'Транспорт', cnt: 2 },
  { word: 'парковк',    category: 'Транспорт', cnt: 2 },
  { word: 'проезд',     category: 'Транспорт', cnt: 2 },
  { word: 'яндекс',     category: 'Транспорт', cnt: 2 },
  { word: 'электричк',  category: 'Транспорт', cnt: 2 },
  // Медицина
  { word: 'аптек',      category: 'Медицина', cnt: 2 },
  { word: 'врач',       category: 'Медицина', cnt: 2 },
  { word: 'клиник',     category: 'Медицина', cnt: 2 },
  { word: 'стоматолог', category: 'Медицина', cnt: 2 },
  { word: 'анализ',     category: 'Медицина', cnt: 2 },
  { word: 'лекарств',   category: 'Медицина', cnt: 2 },
  { word: 'таблетк',    category: 'Медицина', cnt: 2 },
  // Красота
  { word: 'маникюр',    category: 'Красота', cnt: 2 },
  { word: 'педикюр',    category: 'Красота', cnt: 2 },
  { word: 'стрижк',     category: 'Красота', cnt: 2 },
  { word: 'косметик',   category: 'Красота', cnt: 2 },
  { word: 'парфюм',     category: 'Красота', cnt: 2 },
  { word: 'шампун',     category: 'Красота', cnt: 2 },
  { word: 'салон',      category: 'Красота', cnt: 2 },
  { word: 'эпиляц',     category: 'Красота', cnt: 2 },
  // Дом
  { word: 'жкх',        category: 'Дом', cnt: 2 },
  { word: 'квартплат',  category: 'Дом', cnt: 2 },
  { word: 'ипотек',     category: 'Дом', cnt: 2 },
  { word: 'электричеств', category: 'Дом', cnt: 2 },
  { word: 'ремонт',     category: 'Дом', cnt: 2 },
  { word: 'мебель',     category: 'Дом', cnt: 2 },
  // Дети
  { word: 'садик',      category: 'Дети', cnt: 2 },
  { word: 'школ',       category: 'Дети', cnt: 2 },
  { word: 'лагерь',     category: 'Дети', cnt: 2 },
  { word: 'игрушк',     category: 'Дети', cnt: 2 },
  { word: 'детский',    category: 'Дети', cnt: 2 },
  { word: 'кружок',     category: 'Дети', cnt: 2 },
  // Связь
  { word: 'мтс',        category: 'Связь', cnt: 2 },
  { word: 'билайн',     category: 'Связь', cnt: 2 },
  { word: 'мегафон',    category: 'Связь', cnt: 2 },
  { word: 'интернет',   category: 'Связь', cnt: 2 },
  { word: 'телефон',    category: 'Связь', cnt: 2 },
  { word: 'теле',       category: 'Связь', cnt: 2 },
  // Одежда
  { word: 'одежд',      category: 'Одежда', cnt: 2 },
  { word: 'обувь',      category: 'Одежда', cnt: 2 },
  { word: 'zara',       category: 'Одежда', cnt: 2 },
  { word: 'hm',         category: 'Одежда', cnt: 2 },
  // Развлечения
  { word: 'кино',       category: 'Развлечения', cnt: 2 },
  { word: 'театр',      category: 'Развлечения', cnt: 2 },
  { word: 'netflix',    category: 'Развлечения', cnt: 2 },
  { word: 'spotify',    category: 'Развлечения', cnt: 2 },
  { word: 'подписк',    category: 'Развлечения', cnt: 2 },
  { word: 'игр',        category: 'Развлечения', cnt: 2 },
  // Прочее
  { word: 'wildberries', category: 'Прочее', cnt: 2 },
  { word: 'озон',       category: 'Прочее', cnt: 2 },
  { word: 'алиэкспресс', category: 'Прочее', cnt: 2 },
];
